# fly.toml app configuration file generated for locluong-blog on 2025-03-21T15:53:56-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'locluong-blog'
primary_region = 'den'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '5gb'
  cpu_kind = 'shared'
  cpus = 2
