# fly.toml app configuration file generated for personal-blog-withered-wind-5659 on 2025-03-21T15:35:32-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'personal-blog-withered-wind-5659'
primary_region = 'phx'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
